GET http://localhost:3000/

####
GET http://localhost:3000/teste
####
####
GET http://localhost:3000/auth/
####
GET http://localhost:3000/auth/users
####
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "Flavio Gmail",
    "email": "flaviovorthrox@gmail.com",
    "password": "12345"
}
####
POST http://localhost:3000/auth/authenticate
Content-Type: application/json

{
    "email": "flaviovorthrox@gmail.com",
    "password": "12345"
}
####
GET http://localhost:3000/projects

###
GET http://localhost:3000/projects 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NDQyMmJmNjJiMTVkOWJiNzg2YTQ0NSIsImlhdCI6MTY4MjE4NzczMCwiZXhwIjoxNjgyMjc0MTMwfQ.AeYn0-Ulx-HCZqoGakRndVQv5zFi0lPGLAuDuv69_Co

###
POST http://localhost:3000/auth/forgot_password
Content-Type: application/json

{
    "email": "flaviovorthrox@gmail.com"
}

###
POST http://localhost:3000/auth/reset_password
Content-Type: application/json

{
    "email": "flaviovorthrox@gmail.com",
    "token": "797ec42d258fcc65ba9be277e212db7a5974ec5d",
    "password": "12345"
}



